### ISSUE TITLE
淘宝无法联系卖家。

### ISSUE THREAD

**Issue by phoenixxie0** [djun/rx-channel-services#1]
最近几次更新导致了在淘宝内点击联系卖家会显示“聊天窗口打开失败”的情况，禁用本处方后正常。

**Comment by djun** [comment]
收到，谢谢提醒～个人使用淘宝8.11.0是一直正常的，这确实有些奇怪

**Comment by ooroot** [comment]
淘宝9.5.17，同样问题，和卖家沟通无法发送信息
